### ISSUE TITLE
Atom/rss feed is not valid for FreshRSS

### ISSUE THREAD

**Issue by gwen-lg** [rust-adventure/thisweekinbevy#13]
When I tried to add ThisWeekInBeby atom feed in FreshRSS, it's failed with error :
> A feed could not be found at `https://thisweekinbevy.com/feed.xml`; the status code is `200` and content-type is `text/plain; charset=utf-8` [https://thisweekinbevy.com/feed.xml] 

According to Mmdn web doc [Http - Common MIME types](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types), 
the `content-type` of atom/rss feed should be `application/xml` or `application/atom+xml`.

**Comment by ChristopherBiscardi** [comment]
This is in production as of https://github.com/rust-adventure/thisweekinbevy/actions/runs/8381233996

**Comment by gwen-lg** [comment]
I confirm than it's fixed :)
